### ISSUE TITLE
Why saturation correction uses quadratic fit?

### ISSUE THREAD

**Issue by fanurs** [nscl-hira/E15190-Unified-Analysis-Framework#1]
There are two kinds of corrections: Saturation correction and pulse height correction.

For pulse height correction (x: pos, y: light_GM), using quadratic is fine.

For saturation correction (x: pos: y: log(light_R / light_L), I don't think the shape is quadratic at all. See:
https://github.com/nscl-hira/E15190-Unified-Analysis-Framework/blob/837d3ad7a30a2678991bb5e6f9d7ddf0bc890473/calibrations/NWB_Saturation_Correction.txt#L1-L2

And here is the function I was trying to understand just now (but I translated that into Python for readability):
https://github.com/nscl-hira/E15190-Unified-Analysis-Framework/blob/837d3ad7a30a2678991bb5e6f9d7ddf0bc890473/NWPulseHeightCalibration.cpp#L223-L242

Regards,
Fanurs

**Comment by JeongHyeokPark** [comment]
The saturation effect comes with the cutting of the pulse. If the saturated pulses come in, we don't quite get the ADC values of them correctly.
My suspicion is, I think Kuan used  "effective" attenuation length and calculated with "not saturated" pulse signal, because R/L is proportional to exp(2*x/lambda). It is written in his thesis(page70).

But why quadratic? I don't quite get this.

Best Regards,
Jeonghyeok

**Comment by fanurs** [comment]
@JeongHyeokPark I don't think it is quadratic. I am now working on a fix that uses the empirical relation instead.

**Comment by fanurs** [comment]
It turns out that this is not really a mistake. In fact, those quadratic terms are small enough that over the range of `100 cm < x < 100 cm`, the curve is essentially a straight line. What was being done is that, the relation <img src="https://render.githubusercontent.com/render/math?math={\color{gray}\ln(A_\mathrm{L}/A_\mathrm{R})}"> as a function of position is used to recovered saturated ADCs on one side.

The module used in the experiment can only measured up to 4095 channels, so we see the following plots:
<img width="594" alt="image" src="https://user-images.githubusercontent.com/21100851/163272152-cba1676e-912c-4c26-8dd1-5aeca9100393.png">

But if we "push" those saturated data points toward the central line which is mostly straight (and Kuan used quadratic here), then we can produce the plots below, as if the saturated ADCs are recovered:
<img width="590" alt="image" src="https://user-images.githubusercontent.com/21100851/163272474-6821ee11-2114-4989-99d3-e11254ebf717.png">

Finally, this is how a linear fit on the 2D histogram would look like:
![image](https://user-images.githubusercontent.com/21100851/163272695-57343d6c-0643-43f0-9dcc-ca37e78e324a.png)
