### ISSUE TITLE
NWB bar 20 Pulse Height Calibration quadratic term is huge

### ISSUE THREAD

**Issue by fanurs** [nscl-hira/E15190-Unified-Analysis-Framework#2]
The quadratic term `c=0.059115` for NWB bar 20 looks suspiciously huge compared to all the other bars - the rest are smaller than `1e-2`, except for NWB bar 24, which we already know, are bad for runs 4000 and above.
https://github.com/nscl-hira/E15190-Unified-Analysis-Framework/blob/5b2cd0e362438397fdc0d8e247d7e9a84327e9fe/calibrations/NWB_PulseHeightCalibration.dat#L21

**Comment by fanurs** [comment]
The bug is confirmed. See the plots below, generated from the cosmic run 4927. Please just pay attention to the curvature.
<img width="292" alt="image" src="https://user-images.githubusercontent.com/21100851/164246767-08e0ccbe-93e5-4811-8eda-e07d924b5058.png">
<img width="293" alt="image" src="https://user-images.githubusercontent.com/21100851/164246831-aeb1f5c9-f836-4bb9-90bb-cf18198fdf80.png">

**Comment by sompaneru** [comment]
The quadratic term c for bar 3 is similar to bar 24. Do we know the reason behind that?

**Comment by fanurs** [comment]
For bar 3, the old position calibration was bad.

For bar 24, it is bad for all 4xxx runs, including the cosmic run that was used for this calibration.

Anyway, I am working to regenerate all these parameters now.

**Comment by fanurs** [comment]
I'm now looking at the AmBe runs [4798-4802](https://github.com/fanurs/data-analysis-e15190-e14030/blob/63f3977dadbfda8ff53dcf00394cd20e47ce356a/database/runlog/ambe_runs.csv) (inclusive), where we are expected to fit the Compton edge due to the 4.44 MeV gamma ray. Using relativistic kinematics (see https://en.wikipedia.org/wiki/Compton_edge), we expect the Compton edge to occur at ~4.2 MeV.

In the plots below, the x-axis is position in cm, y-axis is geometric mean of `total_L` and `total_R` (ADC values).

The red lines are coming from the quadratic polynomials parametrized as `a + b * x + c * x * x`.
https://github.com/nscl-hira/E15190-Unified-Analysis-Framework/blob/5b2cd0e362438397fdc0d8e247d7e9a84327e9fe/calibrations/NWB_PulseHeightCalibration.dat#L1-L25

---
### Good fit
<img width="277" alt="image" src="https://user-images.githubusercontent.com/21100851/164291347-311f0cbd-ff32-4836-bf87-f65e0f7f56c7.png"><img width="276" alt="image" src="https://user-images.githubusercontent.com/21100851/164291847-0b5f7fa4-bb46-432b-9502-1411861a5263.png">

All bars that are not shown as "bad fits" are just as good as this example too.

---
### Bad fit/data
<img width="276" alt="image" src="https://user-images.githubusercontent.com/21100851/164291576-75e47fe6-b151-451e-8b91-23de97172812.png"><img width="276" alt="image" src="https://user-images.githubusercontent.com/21100851/164291621-18ab240f-d504-453d-8391-4ef6154f03f0.png">
<img width="278" alt="image" src="https://user-images.githubusercontent.com/21100851/164291652-22e42ef4-affb-40d4-8379-3632b07c2ca4.png"><img width="277" alt="image" src="https://user-images.githubusercontent.com/21100851/164291699-a14cda0a-f132-451b-a363-7cdf595f3873.png">

---
### Remarks
- Bar 20, the fit is bad. Known issue.
- Bar 24 is bad for 4xxx runs. Known issue.
- Not sure why bar 1 and bar 13, the data look tilted (fits look symmetric). New issue.
- Bar 3 looks perfectly normal here.
- Next step: Look at another group of AmBe runs, [3072, 3073, 3074](https://github.com/fanurs/data-analysis-e15190-e14030/blob/63f3977dadbfda8ff53dcf00394cd20e47ce356a/database/runlog/ambe_runs.csv)

**Comment by fanurs** [comment]
Things look much better for run [3072](https://github.com/fanurs/data-analysis-e15190-e14030/blob/63f3977dadbfda8ff53dcf00394cd20e47ce356a/database/runlog/ambe_runs.csv), except for bar 20 that is obviously due to bad fitting algorithm. It has become apparent that these runs were used for AmBe calibration, instead of runs [4798-4802](https://github.com/fanurs/data-analysis-e15190-e14030/blob/63f3977dadbfda8ff53dcf00394cd20e47ce356a/database/runlog/ambe_runs.csv).
<img width="275" alt="image" src="https://user-images.githubusercontent.com/21100851/164294581-cd52afa1-0718-4c6b-95ac-1b7db59edf0a.png"><img width="275" alt="image" src="https://user-images.githubusercontent.com/21100851/164294637-5e912204-d6e2-46a4-b1e6-706547c3e9b9.png">
<img width="276" alt="image" src="https://user-images.githubusercontent.com/21100851/164294508-41d9b05e-efbe-4b74-907f-88d88539e954.png"><img width="275" alt="image" src="https://user-images.githubusercontent.com/21100851/164294458-65c4cd91-d04d-40f0-852a-ddeec6f9baa1.png">

Remarks:
- We have to find out, from the data runs, starting from which run NWB bar 1 and bar 13 became asymmetric.
- The plots for NWB bar 20 look bad in both run groups. Even if we improve the fit, I don't think we want to use data from it anyway.
- Again, NWB bar 24 is just bad for run 4xxx.
