### ISSUE TITLE
Double fitting for the re-calibration?

### ISSUE THREAD

**Issue by JeongHyeokPark** [nscl-hira/E15190-Unified-Analysis-Framework#3]
I was trying to compare Experiment data(recalibrated), run 4082~4109 corresponding to 48Ca+64Ni @ 140AMeV, and Simulation for 20 MeV(the most statistical), range between (20-2.5 ~ 20+2.5) MeV. And I also put the result of 40 MeV.

<img width="400" alt="2022-05-06_23-47-01" src="https://user-images.githubusercontent.com/20810896/167156952-7a84647d-6c79-4795-834f-8174c5f301a1.png"> <img width="400" alt="2022-05-07_00-14-13" src="https://user-images.githubusercontent.com/20810896/167161898-dc743190-be92-4c84-99a0-b42345703962.png">

It seems that experiment data has more light than simulation. I think somehow the data has overestimation of the light value.
This issue made me have a look at the "NWB_PulseHeightCalibration.dat".

The formula from ADC channel to Light is below,
<img width="432" alt="2022-05-07_00-00-17" src="https://user-images.githubusercontent.com/20810896/167159347-e4b75fe3-b07a-4a0a-b5f3-4c9c3122a863.png">
which parameter "e" is linear factor.

Let's focus on the parameter "e", of barNum = 1 for now.

**The first parameter file**
https://github.com/nscl-hira/E15190-Unified-Analysis-Framework/blob/752ca6ceab70179a07ff463134e3eb990b482bce/calibrations/NWB_PulseHeightCalibration.dat#L2

**The first "fitted" parameter file**
https://github.com/nscl-hira/E15190-Unified-Analysis-Framework/blob/62c397a75e877eae5a32e29471bd9514abfd36df/calibrations/NWB_PulseHeightCalibration.dat#L2

**The second(?) "fitted" parameter file**
https://github.com/nscl-hira/E15190-Unified-Analysis-Framework/blob/5b2cd0e362438397fdc0d8e247d7e9a84327e9fe/calibrations/NWB_PulseHeightCalibration.dat#L2

Following the time, it seems that parameter "e" getting increased.
Somehow, maybe we double fitted from the original calibration data file.
(e.g. <img width="300" alt="2022-05-07_00-20-25" src="https://user-images.githubusercontent.com/20810896/167162879-3f18e2df-5f2d-401a-8969-703a07b0a43d.png"> )

We should double-check what happened.

**Comment by fanurs** [comment]
@JeongHyeokPark Please check the fix.

The script now always refers to the "pre-2020" calibration file directly from GitHub history.

I shall generate ROOT files for you again, and send them to your server.

![output](https://user-images.githubusercontent.com/21100851/167457894-bd5cbcba-4176-474e-96be-a07cc78b1ef1.png)

**Comment by fanurs** [comment]
Just to show that the resulting ROOT files match the calibration point.
![image](https://user-images.githubusercontent.com/21100851/167509457-e264e141-da41-4933-9dcf-3d7c5ea654c5.png)
